<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfigBankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('config_banks')->delete();

        $codes = 
            array(
                array('code' => "000", 'name' =>"000 - TRANSAKSI TUNAI/NON DHE"),
                array('code' => "001", 'name' =>"001 - BANK INDONESIA"),
                array('code' => "002", 'name' =>"002 - BRI "),
                array('code' => "008", 'name' =>"008 - BANK MANDIRI"),
                array('code' => "009", 'name' =>"009 - BNI "),
                array('code' => "011", 'name' =>"011 - BANK DANAMON"),
                array('code' => "013", 'name' =>"013 - BANK PERMATA"),
                array('code' => "014", 'name' =>"014 - BCA "),
                array('code' => "016", 'name' =>"016 - BII "),
                array('code' => "019", 'name' =>"019 - BANK PANIN"),
                array('code' => "022", 'name' =>"022 - CIMB NIAGA"),
                array('code' => "023", 'name' =>"023 - BANK UOB BUANA"),
                array('code' => "028", 'name' =>"028 - BANK OCBC NISP"),
                array('code' => "031", 'name' =>"031 - CITIBANK"),
                array('code' => "032", 'name' =>"032 - JP MORGAN "),
                array('code' => "033", 'name' =>"033 - BANK OF AMERICA "),
                array('code' => "036", 'name' =>"036 - BANK WINDU"),
                array('code' => "037", 'name' =>"037 - BANK ARTHA GRAHA"),
                array('code' => "040", 'name' =>"040 - BANGKOK BANK"),
                array('code' => "041", 'name' =>"041 - HSBC"),
                array('code' => "042", 'name' =>"042 - BANK OF TOKYO "),
                array('code' => "045", 'name' =>"045 - BANK SUMITOMO "),
                array('code' => "046", 'name' =>"046 - BANK DBS"),
                array('code' => "047", 'name' =>"047 - BANK RESONA PERDANIA"),
                array('code' => "048", 'name' =>"048 - BANK MIZUHO "),
                array('code' => "050", 'name' =>"050 - BANK SC "),
                array('code' => "052", 'name' =>"052 - RBS BANK"),
                array('code' => "054", 'name' =>"054 - BANK CAPITAL"),
                array('code' => "057", 'name' =>"057 - BANK BNP"),
                array('code' => "058", 'name' =>"058 - BANK UOB"),
                array('code' => "059", 'name' =>"059 - BANK KOREA EB INDONESIA "),
                array('code' => "061", 'name' =>"061 - ANZ PANIN BANK"),
                array('code' => "067", 'name' =>"067 - DEUTSCHE BANK "),
                array('code' => "068", 'name' =>"068 - BANK WOORI"),
                array('code' => "069", 'name' =>"069 - BANK OF CHINA "),
                array('code' => "076", 'name' =>"076 - BANK BUMI ARTA"),
                array('code' => "087", 'name' =>"087 - BANK EKONOMI"),
                array('code' => "088", 'name' =>"088 - BANK ANTARDAERAH"),
                array('code' => "089", 'name' =>"089 - RABOBANK"),
                array('code' => "095", 'name' =>"095 - BANK MUTIARA"),
                array('code' => "097", 'name' =>"097 - BANK MAYAPADA "),
                array('code' => "110", 'name' =>"110 - BANK JABAR BANTEN "),
                array('code' => "111", 'name' =>"111 - BANK DKI"),
                array('code' => "112", 'name' =>"112 - BPD DIY "),
                array('code' => "113", 'name' =>"113 - BPD JATENG"),
                array('code' => "114", 'name' =>"114 - BANK JATIM"),
                array('code' => "115", 'name' =>"115 - BPD JAMBI "),
                array('code' => "116", 'name' =>"116 - BPD ACEH"),
                array('code' => "117", 'name' =>"117 - BPD SUMUT "),
                array('code' => "118", 'name' =>"118 - BPD SUMBAR"),
                array('code' => "119", 'name' =>"119 - BPD RIAU"),
                array('code' => "120", 'name' =>"120 - BPD SUMSEL"),
                array('code' => "121", 'name' =>"121 - BANK LAMPUNG"),
                array('code' => "122", 'name' =>"122 - BPD KALSEL"),
                array('code' => "123", 'name' =>"123 - BANK KALBAR "),
                array('code' => "124", 'name' =>"124 - BPD KALTIM"),
                array('code' => "125", 'name' =>"125 - BANK PEMBANGUNAN KALTENG"),
                array('code' => "126", 'name' =>"126 - BPD SULSEL"),
                array('code' => "127", 'name' =>"127 - BANK SULUT"),
                array('code' => "128", 'name' =>"128 - BANK NTB"),
                array('code' => "129", 'name' =>"129 - BPD BALI"),
                array('code' => "130", 'name' =>"130 - BANK NTT"),
                array('code' => "131", 'name' =>"131 - BANK MALUKU "),
                array('code' => "132", 'name' =>"132 - BPD PAPUA "),
                array('code' => "133", 'name' =>"133 - BANK BENGKULU "),
                array('code' => "134", 'name' =>"134 - BPD SULTENG "),
                array('code' => "135", 'name' =>"135 - BPD SULTRA"),
                array('code' => "145", 'name' =>"145 - BANK BNP"),
                array('code' => "146", 'name' =>"146 - BANK SWADESI"),
                array('code' => "147", 'name' =>"147 - BMI "),
                array('code' => "151", 'name' =>"151 - BANK MESTIKA"),
                array('code' => "152", 'name' =>"152 - BANK METRO EXPRESS"),
                array('code' => "153", 'name' =>"153 - BANK SINARMAS "),
                array('code' => "157", 'name' =>"157 - BANK MASPION"),
                array('code' => "161", 'name' =>"161 - BANK GANESHA"),
                array('code' => "164", 'name' =>"164 - BANK ICBC INDONESIA "),
                array('code' => "167", 'name' =>"167 - BANK KESAWAN"),
                array('code' => "200", 'name' =>"200 - BTN "),
                array('code' => "212", 'name' =>"212 - BANK SAUDARA"),
                array('code' => "213", 'name' =>"213 - BTPN"),
                array('code' => "405", 'name' =>"405 - BANK VICTORIA SYARIAH "),
                array('code' => "422", 'name' =>"422 - BRI SYARIAH "),
                array('code' => "425", 'name' =>"425 - BANK JABAR BANTEN SYARIAH "),
                array('code' => "426", 'name' =>"426 - BANK MEGA "),
                array('code' => "427", 'name' =>"427 - BNI SYARIAH "),
                array('code' => "441", 'name' =>"441 - BANK BUKOPIN"),
                array('code' => "451", 'name' =>"451 - BANK SYARIAH MANDIRI"),
                array('code' => "459", 'name' =>"459 - BANK BISNIS "),
                array('code' => "466", 'name' =>"466 - BANK ANDARA "),
                array('code' => "472", 'name' =>"472 - BANK JASA "),
                array('code' => "484", 'name' =>"484 - BANK HANA "),
                array('code' => "485", 'name' =>"485 - BANK BUMIPUTERA "),
                array('code' => "490", 'name' =>"490 - BANK YUDHA BHAKTI "),
                array('code' => "491", 'name' =>"491 - BANK MITRANIAGA "),
                array('code' => "494", 'name' =>"494 - BANK AGRONIAGA"),
                array('code' => "498", 'name' =>"498 - BANK SBI"),
                array('code' => "501", 'name' =>"501 - BANK ROYAL"),
                array('code' => "503", 'name' =>"503 - BANK NATIONALNOBU "),
                array('code' => "506", 'name' =>"506 - BANK SYARIAH MEGA "),
                array('code' => "513", 'name' =>"513 - BANK INA PERDANA"),
                array('code' => "517", 'name' =>"517 - BANK PANIN SYARIAH"),
                array('code' => "520", 'name' =>"520 - BANK PRIMA MASTER "),
                array('code' => "521", 'name' =>"521 - BANK SYARIAH BUKOPIN"),
                array('code' => "523", 'name' =>"523 - BANK DIPO "),
                array('code' => "525", 'name' =>"525 - BANK BARCLAYS "),
                array('code' => "526", 'name' =>"526 - BANK LIMAN"),
                array('code' => "531", 'name' =>"531 - BANK AMIN "),
                array('code' => "535", 'name' =>"535 - BANK KESEJAHTERAAN"),
                array('code' => "536", 'name' =>"536 - BCA SYARIAH "),
                array('code' => "542", 'name' =>"542 - BANK ARTOS"),
                array('code' => "547", 'name' =>"547 - BANK SAHABAT PURBA DANARTA"),
                array('code' => "548", 'name' =>"548 - BANK MAS"),
                array('code' => "553", 'name' =>"553 - BANK MAYORA "),
                array('code' => "555", 'name' =>"555 - BANK INDEX"),
                array('code' => "558", 'name' =>"558 - BANK EKSEKUTIF"),
                array('code' => "559", 'name' =>"559 - BANK CNB"),
                array('code' => "562", 'name' =>"562 - BANK FAMA "),
                array('code' => "564", 'name' =>"564 - BANK SINAR HARAPAN BALI "),
                array('code' => "566", 'name' =>"566 - BANK VICTORIA "),
                array('code' => "567", 'name' =>"567 - BANK HARDA"),
                array('code' => "945", 'name' =>"945 - BANK AGRIS"),
                array('code' => "947", 'name' =>"947 - BANK MAYBANK"),
                array('code' => "948", 'name' =>"948 - BANK OCBC "),
                array('code' => "949", 'name' =>"949 - BANK CHINATRUST "),
                array('code' => "950", 'name' =>"950 - BANK COMMONWEALTH "),
		    );
              
		DB::table('config_bank')->insert($codes);
    }
}
