<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfigJenisSatuanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('config_jenis_satuans')->delete();

        $codes = 
            array(
            array('code' => "1B", 'name' => '1B - DRUM, ALUMINIUM'),
            array('code' => "1D", 'name' => '1D - DRUM, PLYWOOD'),  
            array('code' => "1F", 'name' => '1F - CONTAINER, FLEXIBLE'),
            array('code' => "1G", 'name' => '1G - DRUM, FIBRE'),
            array('code' => "1W", 'name' => '1W - DRUM, WOODEN'),
            array('code' => "2C", 'name' => '2C - BARREL, WOODEN'),
            array('code' => "3A", 'name' => '3A - JERRICAN, STEEL'),
            array('code' => "3H", 'name' => '3H - JERRICAN, PLASTIC'),
            array('code' => "43", 'name' => '43 - BAG, SUPER BULK'),
            array('code' => "44", 'name' => '44 - BAG, POLYBAG'),
            array('code' => "4A", 'name' => '4A - BOX, STEEL'),
            array('code' => "4B", 'name' => '4B - BOX, ALUMINIUM'),
            array('code' => "4C", 'name' => '4C - BOX, NATURAL WOOD'),
            array('code' => "4D", 'name' => '4D - BOX, PLYWOOD'),
            array('code' => "4F", 'name' => '4F - BOX, RECONSTITUTED WOOD'),
            array('code' => "4G", 'name' => '4G - BOX, FIBREBOARD'),
            array('code' => "4H", 'name' => '4H - BOX, PLASTIC'),
            array('code' => "5H", 'name' => '5H - BAG, WOVEN PLASTIC'),
            array('code' => "5L", 'name' => '5L - BAG, TEXTILE'),
            array('code' => "5M", 'name' => '5M - BAG, PAPER'),
            array('code' => "6H", 'name' => '6H - COMPOSITE PACKAGING, PLASTIC RECEPTACLE'),
            array('code' => "6P", 'name' => '6P - COMPOSITE PACKAGING, GLASS RECEPTACLE'),
            array('code' => "7A", 'name' => '7A - CASE, CAR'),
            array('code' => "7B", 'name' => '7B - CASE, WOODEN'),
            array('code' => "8A", 'name' => '8A - PALLET, WOODEN'),
            array('code' => "8B", 'name' => '8B - CRATE, WOODEN'),
            array('code' => "8C", 'name' => '8C - BUNDLE, WOODEN'),
            array('code' => "AA", 'name' => 'AA - INTERMEDIATE BULK CONTAINER, RIGID PLASTIC'),
            array('code' => "AB", 'name' => 'AB - RECEPTACLE, FIBRE'),
            array('code' => "AC", 'name' => 'AC - RECEPTACLE, PAPER'),
            array('code' => "AD", 'name' => 'AD - RECEPTACLE, WOODEN'),
            array('code' => "AE", 'name' => 'AE - AEROSOL'),
            array('code' => "AF", 'name' => 'AF - PALLET, MODULAR, COLLARS 80CMS * 60CMS'),
            array('code' => "AG", 'name' => 'AG - PALLET, SHRINKWRAPPED'),
            array('code' => "AH", 'name' => 'AH - PALLET, 100CMS * 110CMS'),
            array('code' => "AI", 'name' => 'AI - CLAMSHELL'),
            array('code' => "AJ", 'name' => 'AJ - CONE'),
            array('code' => "AL", 'name' => 'AL - BALL'),
            array('code' => "AM", 'name' => 'AM - AMPOULE, NON PROTECTED'),
            array('code' => "AP", 'name' => 'AP - AMPOULE, PROTECTED'),
            array('code' => "AT", 'name' => 'AT - ATOMIZER'),
            array('code' => "AV", 'name' => 'AV - CAPSULE'),
            array('code' => "B4", 'name' => 'B4 - BELT'),
            array('code' => "BA", 'name' => 'BA - BARREL'),
            array('code' => "BB", 'name' => 'BB - BOBBIN'),
            array('code' => "BC", 'name' => 'BC - BOTTLECRATE, BOTTLERACK'),
            array('code' => "BD", 'name' => 'BD - BOARD'),
            array('code' => "BE", 'name' => 'BE - BUNDLE'),
            array('code' => "BF", 'name' => 'BF - BALLOON, NON-PROTECTED'),
            array('code' => "BG", 'name' => 'BG - BAG'),
            array('code' => "BH", 'name' => 'BH - BUNCH'),
            array('code' => "BI", 'name' => 'BI - BIN'),
            array('code' => "BJ", 'name' => 'BJ - BUCKET'),
            array('code' => "BK", 'name' => 'BK - BASKET'),
            array('code' => "BL", 'name' => 'BL - BALE, COMPRESSED'),
            array('code' => "BM", 'name' => 'BM - BASIN'),
            array('code' => "BN", 'name' => 'BN - BALE, NON -COMPRESSED'),
            array('code' => "BO", 'name' => 'BO - BOTTLE, NON-PROTECTED, CYLINDRICAL'),
            array('code' => "BP", 'name' => 'BP - BALLOON, PROTECTED'),
            array('code' => "BQ", 'name' => 'BQ - BOTTLE, PROTECTED CYLINDRICAL'),
            array('code' => "BR", 'name' => 'BR - BAR'),
            array('code' => "BS", 'name' => 'BS - BOTTLE, NON-PROTECTED, BULBOUS'),
            array('code' => "BT", 'name' => 'BT - BOLT'),
            array('code' => "BU", 'name' => 'BU - BUTT'),
            array('code' => "BV", 'name' => 'BV - BOTTLE, PROTECTED BULBOUS'),
            array('code' => "BW", 'name' => 'BW - BOX, FOR LIQUIDS'),
            array('code' => "BX", 'name' => 'BX - BOX'),
            array('code' => "BY", 'name' => 'BY - BOARD, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "BZ", 'name' => 'BZ - BARS, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "CA", 'name' => 'CA - CAN, RECTANGULAR'),
            array('code' => "CB", 'name' => 'CB - BEER CRATE'),
            array('code' => "CC", 'name' => 'CC - CHURN'),
            array('code' => "CD", 'name' => 'CD - CAN, WITH HANDLE AND SPOUT'),
            array('code' => "CE", 'name' => 'CE - CREEL'),
            array('code' => "CF", 'name' => 'CF - COFFER'),
            array('code' => "CG", 'name' => 'CG - CAGE'),
            array('code' => "CH", 'name' => 'CH - CHEST'),
            array('code' => "CI", 'name' => 'CI - CANISTER'),
            array('code' => "CJ", 'name' => 'CJ - COFFIN'),
            array('code' => "CK", 'name' => 'CK - CASK'),
            array('code' => "CL", 'name' => 'CL - COIL'),
            array('code' => "CM", 'name' => 'CM - CARD'),
            array('code' => "CN", 'name' => 'CN - CONT,NOT OTHERWISE SPECFIED AS TRANSPORT EQUIPMENT'),
            array('code' => "CO", 'name' => 'CO - CARBOY, NON-PROTECTED'),
            array('code' => "CP", 'name' => 'CP - CARBOY, PROTECTED'),
            array('code' => "CQ", 'name' => 'CQ - CARTRIDGE'),
            array('code' => "CR", 'name' => 'CR - CRATE'),
            array('code' => "CS", 'name' => 'CS - CASE'),
            array('code' => "CT", 'name' => 'CT - CARTON'),
            array('code' => "CU", 'name' => 'CU - CUP'),
            array('code' => "CV", 'name' => 'CV - COVER'),
            array('code' => "CW", 'name' => 'CW - CAGE, ROLL'),
            array('code' => "CX", 'name' => 'CX - CAN, CYLINDICAL'),
            array('code' => "CY", 'name' => 'CY - CYLINDER'),
            array('code' => "CZ", 'name' => 'CZ - CANVAS'),
            array('code' => "DA", 'name' => 'DA - CRATE, MULTIPLE LAYER, PLASTIC'),
            array('code' => "DB", 'name' => 'DB - CRATE, MULTIPLE LAYER, WOODEN'),
            array('code' => "DC", 'name' => 'DC - CRATE, MULTIPLE LAYER, CARDBOARD'),
            array('code' => "DG", 'name' => 'DG - CAGE, COMMONWEALTH HANDLING EQUIPMENT POOL  (CHEP)'),
            array('code' => "DH", 'name' => 'DH - BOX,COMMNWEALTH HNDLING EQUIPMNT POOL/CHEP,EUROBOX'),
            array('code' => "DI", 'name' => 'DI - DRUM, IRON'),
            array('code' => "DJ", 'name' => 'DJ - DEMIJOHN, NON-PROTECTED'),
            array('code' => "DK", 'name' => 'DK - CRATE, BULK, CARDBOARD'),
            array('code' => "DL", 'name' => 'DL - CRATE, BULK, PLASTIC'),
            array('code' => "DM", 'name' => 'DM - CRATE, BULK, WOODEN'),
            array('code' => "DN", 'name' => 'DN - DISPENSER'),
            array('code' => "DP", 'name' => 'DP - DEMIJOHN, PROTECTED'),
            array('code' => "DR", 'name' => 'DR - DRUM'),
            array('code' => "DS", 'name' => 'DS - TRAY, ONE LAYER NO COVER, PLASTIC'),
            array('code' => "DT", 'name' => 'DT - TRAY, ONE LAYER NO COVER, WOODEN'),
            array('code' => "DU", 'name' => 'DU - TRAY, ONE LAYER NO COVER, POLYSTYRENE'),
            array('code' => "DV", 'name' => 'DV - TRAY, ONE LAYER NO COVER, CARDBOARD'),
            array('code' => "DW", 'name' => 'DW - TRAY, TWO LAYERS NO COVER, PLASTIC TRAY'),
            array('code' => "DX", 'name' => 'DX - TRAY, TWO LAYERS NO COVER, WOODEN'),
            array('code' => "DY", 'name' => 'DY - TRAY, TWO LAYERS NO COVER, CARDBOARD'),
            array('code' => "EC", 'name' => 'EC - BAG, PLASTIC'),
            array('code' => "ED", 'name' => 'ED - CASE, WITH PALLET BASE'),
            array('code' => "EE", 'name' => 'EE - CASE, WITH PALLET BASE, WOODEN'),
            array('code' => "EF", 'name' => 'EF - CASE, WITH PALLET BASE, CARDBOARD'),
            array('code' => "EG", 'name' => 'EG - CASE, WITH PALLET BASE, PLASTIC'),
            array('code' => "EH", 'name' => 'EH - CASE, WITH PALLET BASE, METAL'),
            array('code' => "EI", 'name' => 'EI - CASE, ISOTHERMIC'),
            array('code' => "EN", 'name' => 'EN - ENVELOPE'),
            array('code' => "FB", 'name' => 'FB - FLEXIBAG'),
            array('code' => "FC", 'name' => 'FC - FRUIT CRATE'),
            array('code' => "FD", 'name' => 'FD - FRAMED CRATE'),
            array('code' => "FE", 'name' => 'FE - FLEXITANK'),
            array('code' => "FI", 'name' => 'FI - FIRKIN'),
            array('code' => "FL", 'name' => 'FL - FLASK'),
            array('code' => "FO", 'name' => 'FO - FOOTLOCKER'),
            array('code' => "FP", 'name' => 'FP - FILMPACK'),
            array('code' => "FR", 'name' => 'FR - FRAME'),
            array('code' => "FT", 'name' => 'FT - FOODTAINER'),
            array('code' => "FW", 'name' => 'FW - CART, FLATBED'),
            array('code' => "FX", 'name' => 'FX - BAG, FLEXIBLE CONTAINER'),
            array('code' => "GB", 'name' => 'GB - GAS BOTTLE'),
            array('code' => "GI", 'name' => 'GI - GIRDER'),
            array('code' => "GL", 'name' => 'GL - CONTAINER, GALLON'),
            array('code' => "GR", 'name' => 'GR - RECEPTACLE, GLASS'),
            array('code' => "GU", 'name' => 'GU - TRAY, CONTAINING HORIZONTALLY STACKED FLAT ITEMS'),
            array('code' => "GY", 'name' => 'GY - BAG, GUNNY'),
            array('code' => "GZ", 'name' => 'GZ - GIRDERS, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "HA", 'name' => 'HA - BASKET, WITH HANDLE, PLASTIC'),
            array('code' => "HB", 'name' => 'HB - BASKET, WITH HANDLE, WOODEN'),
            array('code' => "HC", 'name' => 'HC - BASKET, WITH HANDLE, CARDBOARD'),
            array('code' => "HG", 'name' => 'HG - HOGSHEAD'),
            array('code' => "HN", 'name' => 'HN - HANGER'),
            array('code' => "HR", 'name' => 'HR - HAMPER'),
            array('code' => "IA", 'name' => 'IA - PACKAGE, DISPLAY, WOODEN'),
            array('code' => "IB", 'name' => 'IB - PACKAGE, DISPLAY, CARDBOARD'),
            array('code' => "IC", 'name' => 'IC - PACKAGE, DISPLAY, PLASTIC'),
            array('code' => "ID", 'name' => 'ID - PACKAGE, DISPLAY, METAL'),
            array('code' => "IE", 'name' => 'IE - PACKAGE, SHOW'),
            array('code' => "IF", 'name' => 'IF - PACKAGE, FLOW'),
            array('code' => "IG", 'name' => 'IG - PACKAGE, PAPER WRAPPED'),
            array('code' => "IH", 'name' => 'IH - DRUM, PLASTIC'),
            array('code' => "IK", 'name' => 'IK - PACKAGE, CARDBOARD, WITH BOTTLE GRIP-HOLES'),
            array('code' => "IL", 'name' => 'IL - TRAY, RIGID, LIDDED STACKABLE (CEN TS 14482:2002)'),
            array('code' => "IN", 'name' => 'IN - INGOT'),
            array('code' => "IZ", 'name' => 'IZ - INGOTS, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "JB", 'name' => 'JB - BAG, JUMBO'),
            array('code' => "JC", 'name' => 'JC - JERRICAN, RECTANGULAR'),
            array('code' => "JG", 'name' => 'JG - JUG'),
            array('code' => "JR", 'name' => 'JR - JAR'),
            array('code' => "JT", 'name' => 'JT - JUTEBAG'),
            array('code' => "JY", 'name' => 'JY - JERRICAN, CYLINDRICAL'),
            array('code' => "KG", 'name' => 'KG - KEG'),
            array('code' => "KI", 'name' => 'KI - KIT'),
            array('code' => "KR", 'name' => 'KR - KARUNG'),
            array('code' => "LE", 'name' => 'LE - LUGGAGE'),
            array('code' => "LG", 'name' => 'LG - LOG'),
            array('code' => "LT", 'name' => 'LT - LOT'),
            array('code' => "LU", 'name' => 'LU - LUG'),
            array('code' => "LV", 'name' => 'LV - LIFTVAN'),
            array('code' => "LZ", 'name' => 'LZ - LOGS, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "MA", 'name' => 'MA - CRATE, METAL'),
            array('code' => "MB", 'name' => 'MB - MULTIPLY BAG'),
            array('code' => "MC", 'name' => 'MC - MILK CRATE'),
            array('code' => "ME", 'name' => 'ME - CONTAINER, METAL'),
            array('code' => "MR", 'name' => 'MR - RECEPTACLE, METAL'),
            array('code' => "MS", 'name' => 'MS - MULTIWALL SACK'),
            array('code' => "MT", 'name' => 'MT - MAT'),
            array('code' => "MW", 'name' => 'MW - RECEPTACLE, PLASTIC WRAPPED'),
            array('code' => "MX", 'name' => 'MX - MACTH BOX'),
            array('code' => "NA", 'name' => 'NA - NOT AVAILABLE'),
            array('code' => "NE", 'name' => 'NE - UNPACKED OR UNPACKAGED'),
            array('code' => "NF", 'name' => 'NF - UNPACKED OR UNPACKAGED, SINGLE UNIT'),
            array('code' => "NG", 'name' => 'NG - UNPACKED OR UNPACKAGED, MULTIPLE UNITS'),
            array('code' => "NS", 'name' => 'NS - NEST'),
            array('code' => "NT", 'name' => 'NT - NET'),
            array('code' => "NU", 'name' => 'NU - NET, TUBE, PLASTIC'),
            array('code' => "NV", 'name' => 'NV - NET, TUBE, TEXTILE'),
            array('code' => "OA", 'name' => 'OA - PALLET, CHEP 40 CM X 60 CM'),
            array('code' => "OB", 'name' => 'OB - PALLET, CHEP 80 CM X 120 CM'),
            array('code' => "OC", 'name' => 'OC - PALLET, CHEP 100 CM X 120 CM'),
            array('code' => "OD", 'name' => 'OD - PALLET, AS 4068-1993'),
            array('code' => "OE", 'name' => 'OE - PALLET, ISO T11'),
            array('code' => "OF", 'name' => 'OF - PLATFORM, UNSPECIFIED WEIGHT OR DIMENSION'),
            array('code' => "OK", 'name' => 'OK - BLOCK'),
            array('code' => "OT", 'name' => 'OT - OCTABIN'),
            array('code' => "OU", 'name' => 'OU - CONTAINER, OUTER'),
            array('code' => "P2", 'name' => 'P2 - PAN'),
            array('code' => "PA", 'name' => 'PA - PACKET'),
            array('code' => "PB", 'name' => 'PB - PALLET, BOX COMBINED OPEN-ENDED BOX AND PALLET'),
            array('code' => "PC", 'name' => 'PC - PARCEL'),
            array('code' => "PD", 'name' => 'PD - PALLET, MODULAR, COLLARS 80CMS * 100CMS'),
            array('code' => "PE", 'name' => 'PE - PALLET, MODULAR, COLLARS 80CMS * 120CMS'),
            array('code' => "PF", 'name' => 'PF - PEN'),
            array('code' => "PG", 'name' => 'PG - PLATE'),
            array('code' => "PH", 'name' => 'PH - PITCHER'),
            array('code' => "PI", 'name' => 'PI - PIPE'),
            array('code' => "PJ", 'name' => 'PJ - PUNNET'),
            array('code' => "PK", 'name' => 'PK - PACKAGE'),
            array('code' => "PL", 'name' => 'PL - PAIL'),
            array('code' => "PN", 'name' => 'PN - PLANK'),
            array('code' => "PO", 'name' => 'PO - POUCH'),
            array('code' => "PP", 'name' => 'PP - PIECE'),
            array('code' => "PR", 'name' => 'PR - RECEPTACLE, PLASTIC'),
            array('code' => "PT", 'name' => 'PT - POT'),
            array('code' => "PU", 'name' => 'PU - TRAY'),
            array('code' => "PV", 'name' => 'PV - PIPES, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "PX", 'name' => 'PX - PALLET'),
            array('code' => "PY", 'name' => 'PY - PLATES, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "PZ", 'name' => 'PZ - PIPES, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "QA", 'name' => 'QA - DRUM, STEEL, NON-REMOVABLE HEAD'),
            array('code' => "QB", 'name' => 'QB - DRUM, STEEL, REMOVABLE HEAD'),
            array('code' => "QC", 'name' => 'QC - DRUM, ALUMINIUM, NON-REMOVABLE HEAD'),
            array('code' => "QD", 'name' => 'QD - DRUM, ALUMINIUM, REMOVABLE HEAD'),
            array('code' => "QF", 'name' => 'QF - DRUM, PLASTIC, NON-REMOVABLE HEAD'),
            array('code' => "QG", 'name' => 'QG - DRUM, PLASTIC, REMOVABLE HEAD'),
            array('code' => "QH", 'name' => 'QH - BARREL, WOODEN, BUNG TYPE'),
            array('code' => "QJ", 'name' => 'QJ - BARREL, WOODEN, REMOVABLE HEAD'),
            array('code' => "QK", 'name' => 'QK - JERRICAN, STEEL, NON-REMOVABLE HEAD'),
            array('code' => "QL", 'name' => 'QL - JERRICAN, STEEL, REMOVABLE HEAD'),
            array('code' => "QM", 'name' => 'QM - JERRICAN, PLASTIC, NON-REMOVABLE HEAD'),
            array('code' => "QN", 'name' => 'QN - JERRICAN, PLASTIC, REMOVABLE HEAD'),
            array('code' => "QP", 'name' => 'QP - BOX, WOODEN, NATURAL WOOD, ORDINARY'),
            array('code' => "QQ", 'name' => 'QQ - BOX, WOODEN, NATURAL WOOD, WITH SIFT PROOF WALLS'),
            array('code' => "QR", 'name' => 'QR - BOX, PLASTIC, EXPANDED'),
            array('code' => "QS", 'name' => 'QS - BOX, PLASTIC, SOLID'),
            array('code' => "RD", 'name' => 'RD - ROD'),
            array('code' => "RG", 'name' => 'RG - RING'),
            array('code' => "RJ", 'name' => 'RJ - RACK, CLOTHING HANGER'),
            array('code' => "RK", 'name' => 'RK - RACK'),
            array('code' => "RL", 'name' => 'RL - REEL'),
            array('code' => "RO", 'name' => 'RO - ROLL'),
            array('code' => "RT", 'name' => 'RT - REDNET'),
            array('code' => "RZ", 'name' => 'RZ - RODS, IN BUNDLE/ BUNCH/TRUSS'),
            array('code' => "SA", 'name' => 'SA - SACK'),
            array('code' => "SB", 'name' => 'SB - SLAB'),
            array('code' => "SC", 'name' => 'SC - SHALLOW CRATE'),
            array('code' => "SD", 'name' => 'SD - SPINDLE'),
            array('code' => "SE", 'name' => 'SE - SEA-CHEST'),
            array('code' => "SH", 'name' => 'SH - SACHET'),
            array('code' => "SI", 'name' => 'SI - SKID'),
            array('code' => "SK", 'name' => 'SK - SKELETON CASE'),
            array('code' => "SL", 'name' => 'SL - SLIPSHEET'),
            array('code' => "SM", 'name' => 'SM - SHEETMETAL'),
            array('code' => "SO", 'name' => 'SO - SPOOL'),
            array('code' => "SP", 'name' => 'SP - SHEET, PLASTIC WRAPPING'),
            array('code' => "SS", 'name' => 'SS - CASE, STEEL'),
            array('code' => "ST", 'name' => 'ST - SHEET'),
            array('code' => "SU", 'name' => 'SU - SUITCASE'),
            array('code' => "SV", 'name' => 'SV - ENVELOPE, STEEL'),
            array('code' => "SW", 'name' => 'SW - SHRINKWRAPPED'),
            array('code' => "SX", 'name' => 'SX - SET'),
            array('code' => "SY", 'name' => 'SY - SLEEVE'),
            array('code' => "SZ", 'name' => 'SZ - SHEETS, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "T1", 'name' => 'T1 - TABLET'),
            array('code' => "TB", 'name' => 'TB - TUB'),
            array('code' => "TC", 'name' => 'TC - TEA-CHEST'),
            array('code' => "TD", 'name' => 'TD - COLLAPSIBLE TUBE'),
            array('code' => "TE", 'name' => 'TE - TYRE'),
            array('code' => "TG", 'name' => 'TG - TANK CONTAINER, GENERIC'),
            array('code' => "TI", 'name' => 'TI - TIERCE'),
            array('code' => "TK", 'name' => 'TK - TANK, RECTANGULAR'),
            array('code' => "TL", 'name' => 'TL - TUB, WITH LID'),
            array('code' => "TN", 'name' => 'TN - TIN'),
            array('code' => "TO", 'name' => 'TO - TUN'),
            array('code' => "TP", 'name' => 'TP - TRAY'),
            array('code' => "TR", 'name' => 'TR - TRUNK'),
            array('code' => "TS", 'name' => 'TS - TRUSS'),
            array('code' => "TT", 'name' => 'TT - BAG, TOTE'),
            array('code' => "TU", 'name' => 'TU - TUBE'),
            array('code' => "TV", 'name' => 'TV - TUBE, WITH NOZZLE'),
            array('code' => "TW", 'name' => 'TW - PALLET, TRIWALL'),
            array('code' => "TY", 'name' => 'TY - TANK, CYLINDRICAL'),
            array('code' => "TZ", 'name' => 'TZ - TUBES, IN BUNDLE/BUNCH/TRUSS'),
            array('code' => "UC", 'name' => 'UC - UNCAGED'),
            array('code' => "UN", 'name' => 'UN - UNPACKAGE'),
            array('code' => "VA", 'name' => 'VA - VAT'),
            array('code' => "VG", 'name' => 'VG - BULK, GAS ( AT 1031 MBAR AND 15C )'),
            array('code' => "VI", 'name' => 'VI - VIAL'),
            array('code' => "VK", 'name' => 'VK - VANPACK'),
            array('code' => "VL", 'name' => 'VL - BULK, LIQUID'),
            array('code' => "VN", 'name' => 'VN - VEHICLE'),
            array('code' => "VO", 'name' => 'VO - BULK, SOLID, LARGE PARTICLES ("NODULES")'),
            array('code' => "VP", 'name' => 'VP - VACUUMPACKED'),
            array('code' => "VQ", 'name' => 'VQ - BULK,LIQUEFIED GAS (AT ABNORML TEMPRTURE/PRESSURE)'),
            array('code' => "VR", 'name' => 'VR - BULK, SOLID, GRANULAR PARTICLES ("GRAINS")'),
            array('code' => "VS", 'name' => 'VS - BULK, SCRAP METAL'),
            array('code' => "VY", 'name' => 'VY - BULK, SOLID, FINE PARTICLES ("POWDERS")'),
            array('code' => "WA", 'name' => 'WA - INTERMEDIATE BULK CONTAINER'),
            array('code' => "WB", 'name' => 'WB - WICKERBOTTLE'),
            array('code' => "WC", 'name' => 'WC - INTERMEDIATE BULK CONTAINER, STEEL'),
            array('code' => "WD", 'name' => 'WD - INTERMEDIATE BULK CONTAINER, ALUMINIUM'),
            array('code' => "WF", 'name' => 'WF - INTERMEDIATE BULK CONTAINER, METAL'),
            array('code' => "WG", 'name' => 'WG - INTERMEDIATE BULK CONT,STEEL,PRESSURISED &gt;10 KPA'),
            array('code' => "WH", 'name' => 'WH - INTERMEDT BULK CONT,ALUMINIUM,PRESSURISED &gt;10 KPA'),
            array('code' => "WJ", 'name' => 'WJ - INTERMEDIATE BULK CONTAINER,METAL, PRESSURE 10 KPA'),
            array('code' => "WK", 'name' => 'WK - INTERMEDIATE BULK CONTAINER, STEEL, LIQUID'),
            array('code' => "WL", 'name' => 'WL - INTERMEDIATE BULK CONTAINER, ALUMINIUM, LIQUID'),
            array('code' => "WM", 'name' => 'WM - INTERMEDIATE BULK CONTAINER, METAL, LIQUID'),
            array('code' => "WN", 'name' => 'WN - INTERMD BULK CONT,WOVEN PLASTIC,WITHOUT COAT/LINER'),
            array('code' => "WP", 'name' => 'WP - INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, COATED'),
            array('code' => "WQ", 'name' => 'WQ - INTERMEDIATE BULK CONT,WOVEN PLASTIC,WITH LINER'),
            array('code' => "WR", 'name' => 'WR - INTERMEDT BULK CONT,WOVEN PLASTIC,COATED AND LINER'),
            array('code' => "WS", 'name' => 'WS - INTERMEDIATE BULK CONTAINER, PLASTIC FILM'),
            array('code' => "WT", 'name' => 'WT - INTERMEDIATE BULK CONT,TEXTILE WITH OUT COAT/LINER'),
            array('code' => "WU", 'name' => 'WU - INTERMDTE BULK CONT,NATURAL WOOD,WITH INNER LINER'),
            array('code' => "WV", 'name' => 'WV - INTERMEDIATE BULK CONTAINER, TEXTILE, COATED'),
            array('code' => "WW", 'name' => 'WW - INTERMEDIATE BULK CONTAINER, TEXTILE, WITH LINER'),
            array('code' => "WX", 'name' => 'WX - INTERMEDIATE BULK CONT,TEXTILE,COATED AND LINER'),
            array('code' => "WY", 'name' => 'WY - INTERMEDIATE BULK CONT,PLYWOOD,WITH INNER LINER'),
            array('code' => "WZ", 'name' => 'WZ - INTERMD BULK CONT,RECONSTTTD WOOD,WITH INNER LINER'),
            array('code' => "XA", 'name' => 'XA - BAG, WOVEN PLASTIC, WITHOUT INNER COAT/LINER'),
            array('code' => "XB", 'name' => 'XB - BAG, WOVEN PLASTIC, SIFT PROOF'),
            array('code' => "XC", 'name' => 'XC - BAG, WOVEN PLASTIC, WATER RESISTANT'),
            array('code' => "XD", 'name' => 'XD - BAG, PLASTICS FILM'),
            array('code' => "XF", 'name' => 'XF - BAG, TEXTILE, WITHOUT INNER COAT/LINER'),
            array('code' => "XG", 'name' => 'XG - BAG, TEXTILE, SIFT PROOF'),
            array('code' => "XH", 'name' => 'XH - BAG, TEXTILE, WATER RESISTANT'),
            array('code' => "XJ", 'name' => 'XJ - BAG, PAPER, MULTI-WALL'),
            array('code' => "XK", 'name' => 'XK - BAG, PAPER, MULTI-WALL, WATER RESISTANT'),
            array('code' => "YA", 'name' => 'YA - COMPSITE PACKGING,PLASTIC RECEPTACLE IN STEEL DRUM'),
            array('code' => "YB", 'name' => 'YB - COMPSTE PACKGNG,PLASTC RECPTCLE IN STEEL CRATE BOX'),
            array('code' => "YC", 'name' => 'YC - COMPSTE PACKGNG,PLASTIC RECPTCLE IN ALUMINIUM DRUM'),
            array('code' => "YD", 'name' => 'YD - COMPSTE PACKGNG,PLASTIC RECPTCLE IN ALUMNIUM CRATE'),
            array('code' => "YF", 'name' => 'YF - COMPSITE PACKGING,PLASTIC RECEPTACLE IN WOODEN BOX'),
            array('code' => "YG", 'name' => 'YG - COMPSTE PACKGNG,PLASTIC RECEPTACLE IN PLYWOOD DRUM'),
            array('code' => "YH", 'name' => 'YH - COMPSTE PACKGING,PLASTIC RECEPTACLE IN PLYWOOD BOX'),
            array('code' => "YJ", 'name' => 'YJ - COMPSITE PACKGING,PLASTIC RECEPTACLE IN FIBRE DRUM'),
            array('code' => "YK", 'name' => 'YK - COMPSTE PACKGNG,PLASTIC RECPTCLE IN FIBREBOARD BOX'),
            array('code' => "YL", 'name' => 'YL - COMPSTE PACKGNG,PLASTIC RECEPTACLE IN PLASTIC DRUM'),
            array('code' => "YM", 'name' => 'YM - COMPSITE PACKGNG,PLSTC RECPTCLE IN SOLID PLSTC BOX'),
            array('code' => "YN", 'name' => 'YN - COMPOSITE PACKAGING,GLASS RECEPTACLE IN STEEL DRUM'),
            array('code' => "YP", 'name' => 'YP - COMPSTE PACKGNG,GLASS RECPTACLE IN STEEL CRATE BOX'),
            array('code' => "YQ", 'name' => 'YQ - COMPSTE PACKGNG,GLASS RECEPTACLE IN ALUMINIUM DRUM'),
            array('code' => "YR", 'name' => 'YR - COMPSTE PACKGNG,GLASS RECPTACLE IN ALUMINIUM CRATE'),
            array('code' => "YS", 'name' => 'YS - COMPOSITE PACKAGING,GLASS RECEPTACLE IN WOODEN BOX'),
            array('code' => "YT", 'name' => 'YT - COMPSITE PACKGING,GLASS RECEPTACLE IN PLYWOOD DRUM'),
            array('code' => "YV", 'name' => 'YV - COMPSTE PACKGNG,GLASS RECPTCLE IN WICKRWORK HAMPER'),
            array('code' => "YW", 'name' => 'YW - COMPOSITE PACKAGING,GLASS RECEPTACLE IN FIBRE DRUM'),
            array('code' => "YX", 'name' => 'YX - COMPSTE PACKGNG,GLASS RECEPTACLE IN FIBREBOARD BOX'),
            array('code' => "YY", 'name' => 'YY - COMPSTE PCKGNG,GLSS RECPTCL IN EXPNDBL PLASTC PACK'),
            array('code' => "YZ", 'name' => 'YZ - COMPSITE PACKGNG,GLASS RECPTCLE IN SOLID PLSTC PCK'),
            array('code' => "ZA", 'name' => 'ZA - INTERMEDIATE BULK CONTAINER, PAPER, MULTI-WALL'),
            array('code' => "ZB", 'name' => 'ZB - BAG, LARGE'),
            array('code' => "ZC", 'name' => 'ZC - INTERMD BULK CONT,PAPER,MULTI-WALL,WATER RESISTANT'),
            array('code' => "ZD", 'name' => 'ZD - INTERMD BULK CONT,RGD PLSTC,W/STRCTRL EQUIPM,SOLID'),
            array('code' => "ZF", 'name' => 'ZF - INTERMD BULK CONT,RGID PLSTC,FREESTANDNG,SOLDS'),
            array('code' => "ZG", 'name' => 'ZG - INTERMDBULK CNT,RGD PLSTC,W/STRCTRL EQUIPM,PRESSRD'),
            array('code' => "ZH", 'name' => 'ZH - INTERMD BULK CONT,RGD PLSTC,FREESTND,PRESSURISED'),
            array('code' => "ZJ", 'name' => 'ZJ - INTERMD BULK CONT,RGD PLSTC,W/STRCTRL EQUIPM,LQUID'),
            array('code' => "ZK", 'name' => 'ZK - INTERMD BULK CONT,RGID PLSTC,FREESTANDING,LIQUIDS'),
            array('code' => "ZL", 'name' => 'ZL - INTERMD BULK CONT,COMPOSITE,RIGID PLASTIC,SOLIDS'),
            array('code' => "ZM", 'name' => 'ZM - INTERMD BULK CONT,COMPSTE,FLEXBL PLASTIC, SOLIDS'),
            array('code' => "ZN", 'name' => 'ZN - INTERMD BULK CONT,COMPSIT,RGID PLSTC,PRESSURISED'),
            array('code' => "ZP", 'name' => 'ZP - INTERMD BULK CONT,COMPSIT,FLEXBL PLSTC,PRESSURISED'),
            array('code' => "ZQ", 'name' => 'ZQ - INTERMD BULK CONT,COMPOSITE,RIGID PLASTIC,LIQUIDS'),
            array('code' => "ZR", 'name' => 'ZR - INTERMD BULK CONT,COMPSITE,FLEXIBLE PLASTC,LIQUIDS'),
            array('code' => "ZS", 'name' => 'ZS - INTERMEDIATE BULK CONTAINER, COMPOSITE'),
            array('code' => "ZT", 'name' => 'ZT - INTERMEDIATE BULK CONTAINER, FIBREBOARD'),
            array('code' => "ZU", 'name' => 'ZU - INTERMEDIATE BULK CONTAINER, FLEXIBLE'),
            array('code' => "ZV", 'name' => 'ZV - INTERMEDIATE BULK CONTAINER,METAL,OTHER THAN STEEL'),
            array('code' => "ZW", 'name' => 'ZW - INTERMEDIATE BULK CONTAINER, NATURAL WOOD'),
            array('code' => "ZX", 'name' => 'ZX - INTERMEDIATE BULK CONTAINER, PLYWOOD'),
            array('code' => "ZY", 'name' => 'ZY - INTERMEDIATE BULK CONTAINER, RECONSTITUTED WOOD'),
            array('code' => "ZZ", 'name' => 'ZZ - MUTUALLY DEFINED'),
		    );

		DB::table('config_jenis_satuans')->insert($codes);
    }
}
